### ISSUE TITLE
Unit tests aren't passing on maven install

### ISSUE THREAD

**Issue by bdavis252** [wingify/vwo-java-sdk#11]
[ERROR] Tests run: 5, Failures: 4, Errors: 0, Skipped: 0, Time elapsed: 6.354 s <<< FAILURE! - in com.vwo.tests.e2e.EventBatchingTests
[ERROR] enqueueAndFlushEventsTests  Time elapsed: 0.225 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <1>
        at com.vwo.tests.e2e.EventBatchingTests.enqueueAndFlushEventsTests(EventBatchingTests.java:62)

[ERROR] flushQueueOnTimerExpiredTest  Time elapsed: 6.097 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <0>
        at com.vwo.tests.e2e.EventBatchingTests.flushQueueOnTimerExpiredTest(EventBatchingTests.java:109)

[ERROR] flushEventsAPITest  Time elapsed: 0.014 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <0>
        at com.vwo.tests.e2e.EventBatchingTests.flushEventsAPITest(EventBatchingTests.java:124)

[ERROR] flushQueueOnMaxEventsTest  Time elapsed: 0.012 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <2> but was: <0>
        at com.vwo.tests.e2e.EventBatchingTests.flushQueueOnMaxEventsTest(EventBatchingTests.java:83)

**Comment by rohitesh-wingify** [comment]
Hello @bdavis252. As we have replied to you over email, the repo you need is this : https://github.com/wingify/vwo-fme-java-sdk/

We will also look into this and fix the tests for this SDK as well.
